# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 665)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/icon/telegram.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_fun_private_send = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_fun_private_send.setObjectName("pushButton_fun_private_send")
        self.gridLayout.addWidget(self.pushButton_fun_private_send, 0, 0, 1, 1)
        self.pushButton_fun_group_send = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_fun_group_send.setObjectName("pushButton_fun_group_send")
        self.gridLayout.addWidget(self.pushButton_fun_group_send, 1, 0, 1, 1)
        self.pushButton_fun_collect = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_fun_collect.setObjectName("pushButton_fun_collect")
        self.gridLayout.addWidget(self.pushButton_fun_collect, 2, 0, 1, 1)
        self.pushButton_fun_get_user = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_fun_get_user.setObjectName("pushButton_fun_get_user")
        self.gridLayout.addWidget(self.pushButton_fun_get_user, 3, 0, 1, 1)
        self.pushButton_fun_invite = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_fun_invite.setObjectName("pushButton_fun_invite")
        self.gridLayout.addWidget(self.pushButton_fun_invite, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(471, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "注册校验"))
        self.groupBox.setTitle(_translate("Form", "功能选择"))
        self.pushButton_fun_private_send.setText(_translate("Form", "发送私聊消息"))
        self.pushButton_fun_group_send.setText(_translate("Form", "发送群组消息"))
        self.pushButton_fun_collect.setText(_translate("Form", "群组采集"))
        self.pushButton_fun_get_user.setText(_translate("Form", "群成员采集"))
        self.pushButton_fun_invite.setText(_translate("Form", "邀请用户进群"))
import source.source_rc
